import { execFile as execFileCallback } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, mkdtemp, readFile, readdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { installHost, preserveLocalCodexModelOverride, uninstallHost, type InstallOptions } from "../src/install.js";
import { resolveHostPaths, type PathEnvironment } from "../src/host-paths.js";
import { parseFrontmatter, parseJsonc, parseToml } from "../src/parsers.js";
import type { Host } from "../src/types.js";

const execFile = promisify(execFileCallback);
const sourceRoot = path.resolve(import.meta.dirname, "..", "..");
const hosts: Host[] = ["codex", "claude", "opencode", "copilot"];

describe("managed native installation", () => {
  it.each(hosts)("installs %s at isolated user and project native paths", async (host) => {
    const fixture = await fixtureEnvironment(`kit-install-${host}-`);
    for (const scope of ["user", "project"] as const) {
      const options = baseOptions(host, scope, fixture);
      const result = await installHost(options);
      expect(result.actions.some((action) => /WRITE|BLOCK/.test(action))).toBe(true);
      const paths = await resolveHostPaths(host, scope, fixture.repo, fixture.context);
      await expect(readFile(paths.instruction, "utf8")).resolves.toContain("agentic-coding-kit:start");
      const agentNames = await readdir(paths.agents);
      expect(agentNames.some((name) => /reviewer/.test(name))).toBe(true);
      const skill = await readFile(path.join(paths.skills, "build", "SKILL.md"), "utf8");
      expect(parseFrontmatter(skill).data.name).toBe("build");
      const reviewer = await readFile(path.join(paths.agents, host === "codex" ? "reviewer.toml" : host === "copilot" ? "reviewer.agent.md" : "reviewer.md"), "utf8");
      if (host === "codex") expect(parseToml(reviewer)).toMatchObject({ name: "reviewer" });
      else expect(parseFrontmatter(reviewer).data.description).toEqual(expect.any(String));
      await installHost(options);
      expect((await readFile(paths.instruction, "utf8")).split("agentic-coding-kit:start").length - 1).toBe(1);
    }
  }, 30_000);

  it("shares one project AGENTS block across Codex, OpenCode, and Copilot", async () => {
    const fixture = await fixtureEnvironment("kit-shared-block-");
    for (const host of ["codex", "opencode", "copilot"] as Host[]) await installHost(baseOptions(host, "project", fixture));
    const agents = await readFile(path.join(fixture.repo, "AGENTS.md"), "utf8");
    expect(agents.split("agentic-coding-kit:start").length - 1).toBe(1);
    expect(await readFile(path.join(fixture.repo, ".github", "copilot-instructions.md"), "utf8")).toContain("Shared orchestration rules");
  }, 30_000);

  it("preserves an explicit local Codex agent model override during an update", async () => {
    const fixture = await fixtureEnvironment("kit-codex-model-override-");
    const options = baseOptions("codex", "user", fixture);
    await installHost(options);
    const paths = await resolveHostPaths("codex", "user", undefined, fixture.context);
    const scout = path.join(paths.agents, "repo-scout.toml");
    await writeFile(scout, `${await readFile(scout, "utf8")}model = "gpt-5.6-luna"\nmodel_reasoning_effort = "medium"\n`, "utf8");
    await installHost(options);
    expect(await readFile(scout, "utf8")).toContain('model = "gpt-5.6-luna"');
  }, 30_000);

  it("reapplies a model-only Codex override when the generated prompt changes", () => {
    const oldGenerated = '# @generated by Agentic Coding Kit v6; source=x; sourceId=agent:repo-scout\nname = "repo-scout"\ndeveloper_instructions = "old"\n';
    const existing = `${oldGenerated}model = "gpt-5.6-luna"\nmodel_reasoning_effort = "medium"\n`;
    const newGenerated = oldGenerated.replace('"old"', '"new"');
    const previous = { path: "repo-scout.toml", sha256: createHash("sha256").update(oldGenerated).digest("hex"), ownership: "managed" as const, sourceId: "agent:repo-scout" };
    const updated = preserveLocalCodexModelOverride("repo-scout.toml", existing, newGenerated, previous);
    expect(updated).toContain('developer_instructions = "new"');
    expect(updated).toContain('model = "gpt-5.6-luna"');
  });

  it("supports core/full, command modes, conflicts, force backups, and owned uninstall", async () => {
    const fixture = await fixtureEnvironment("kit-managed-lifecycle-");
    const options = baseOptions("opencode", "user", fixture);
    await installHost({ ...options, profile: "full", commands: "on" });
    const paths = await resolveHostPaths("opencode", "user", undefined, fixture.context);
    await expect(readFile(path.join(paths.agents, "browser-qa.md"), "utf8")).resolves.toContain("Browser QA");
    await expect(readFile(path.join(paths.commands!, "build.md"), "utf8")).resolves.toContain("$ARGUMENTS");
    await installHost({ ...options, profile: "core", commands: "off" });
    await expect(readFile(path.join(paths.agents, "browser-qa.md"), "utf8")).rejects.toThrow();
    await expect(readFile(path.join(paths.agents, "security-reviewer.md"), "utf8")).resolves.toContain("Security Reviewer");
    await expect(readFile(path.join(paths.skills, "threat-model", "SKILL.md"), "utf8")).resolves.toContain("# Threat Model");
    await expect(readFile(path.join(paths.commands!, "build.md"), "utf8")).rejects.toThrow();

    const reviewer = path.join(paths.agents, "reviewer.md");
    await writeFile(reviewer, `${await readFile(reviewer, "utf8")}\nlocal edit\n`, "utf8");
    await expect(installHost(options)).rejects.toThrow(/conflict/i);
    await installHost({ ...options, force: true });
    expect((await readdir(paths.agents)).some((name) => name.includes("backup"))).toBe(true);
    const custom = path.join(paths.agents, "custom.md");
    await writeFile(custom, "custom\n", "utf8");
    await uninstallHost(options);
    await expect(readFile(reviewer, "utf8")).rejects.toThrow();
    await expect(readFile(custom, "utf8")).resolves.toBe("custom\n");
  }, 30_000);

  it("preserves JSONC/TOML settings and restores managed keys on uninstall", async () => {
    const fixture = await fixtureEnvironment("kit-config-preserve-");
    const claudePaths = await resolveHostPaths("claude", "project", fixture.repo, fixture.context);
    await mkdir(path.dirname(claudePaths.localSettings!), { recursive: true });
    await writeFile(claudePaths.localSettings!, '{\n  // keep\n  "theme": "dark",\n  "autoMemoryEnabled": true\n}\n', "utf8");
    const claude = { ...baseOptions("claude", "project", fixture), memory: "wiki-only" as const };
    await installHost(claude);
    expect(parseJsonc(await readFile(claudePaths.localSettings!, "utf8"))).toMatchObject({ theme: "dark", autoMemoryEnabled: false });
    await uninstallHost(claude);
    expect(parseJsonc(await readFile(claudePaths.localSettings!, "utf8"))).toMatchObject({ theme: "dark", autoMemoryEnabled: true });
    expect(await readFile(claudePaths.localSettings!, "utf8")).toContain("// keep");

    const codexPaths = await resolveHostPaths("codex", "user", undefined, fixture.context);
    await mkdir(path.dirname(codexPaths.config!), { recursive: true });
    await writeFile(codexPaths.config!, '# agentic-coding-kit:start\n[profiles.agentic-kit]\nmodel = "old"\n\n[projects.\'c:\\repo\']\ntrust_level = "trusted"\n# agentic-coding-kit:end\n\n[mcp_servers.keep]\ncommand = "keep"\n', "utf8");
    const codex = { ...baseOptions("codex", "user", fixture), security: "guarded" as const };
    await installHost(codex);
    const installedCodex = parseToml(await readFile(codexPaths.config!, "utf8"));
    expect(installedCodex).toHaveProperty("mcp_servers.keep.command", "keep");
    expect((installedCodex.projects as Record<string, unknown>)["c:\\repo"]).toMatchObject({ trust_level: "trusted" });
    expect(installedCodex).toMatchObject({ approval_policy: "on-request", sandbox_mode: "workspace-write" });
    expect(installedCodex).not.toHaveProperty("model");
    expect(installedCodex).not.toHaveProperty("model_reasoning_effort");
    expect(installedCodex).not.toHaveProperty("profiles.agentic-kit");
    await uninstallHost(codex);
    expect(parseToml(await readFile(codexPaths.config!, "utf8"))).toHaveProperty("mcp_servers.keep.command", "keep");
  }, 30_000);

  it("dry-run writes nothing and malformed blocks require force", async () => {
    const fixture = await fixtureEnvironment("kit-dry-run-");
    const options = baseOptions("codex", "project", fixture);
    await installHost({ ...options, dryRun: true });
    await expect(readFile(path.join(fixture.repo, "AGENTS.md"), "utf8")).rejects.toThrow();
    await writeFile(path.join(fixture.repo, "AGENTS.md"), "user\n<!-- agentic-coding-kit:start -->\nbroken\n", "utf8");
    await expect(installHost(options)).rejects.toThrow(/malformed|duplicate/i);
    await installHost({ ...options, force: true });
    expect((await readFile(path.join(fixture.repo, "AGENTS.md"), "utf8")).split("agentic-coding-kit:start").length - 1).toBe(1);
  }, 30_000);
});

function baseOptions(host: Host, scope: "user" | "project", fixture: Awaited<ReturnType<typeof fixtureEnvironment>>): InstallOptions {
  return { repoRoot: sourceRoot, host, scope, repo: scope === "project" ? fixture.repo : undefined, profile: "core", security: "preserve", memory: "preserve", commands: "auto", setDefaultAgent: false, dryRun: false, force: false, yes: false, verbose: false, pathContext: fixture.context };
}

async function fixtureEnvironment(prefix: string): Promise<{ home: string; repo: string; context: PathEnvironment }> {
  const root = await mkdtemp(path.join(tmpdir(), prefix));
  const home = path.join(root, "home space Ω");
  const repo = path.join(root, "repo space Ω");
  await mkdir(home, { recursive: true });
  await mkdir(repo, { recursive: true });
  await execFile("git", ["init", "--quiet"], { cwd: repo });
  const env = { ...process.env, CODEX_HOME: path.join(home, "codex"), CLAUDE_CONFIG_DIR: path.join(home, "claude"), OPENCODE_CONFIG_DIR: path.join(home, "opencode"), COPILOT_HOME: path.join(home, "copilot") };
  return { home, repo, context: { home, platform: process.platform, env } };
}
