#!/usr/bin/env pwsh
# harness-review.ps1
# Lifecycle for harness proposals generated by harness-propose.ps1.
#   - List: show all pending/decided proposals
#   - Show: print full proposal body
#   - Decide: mark a proposal accepted/rejected/deferred
#
# Decisions append to ${AGENTS_HOME}/proposals/decisions.jsonl. Once recorded,
# harness-propose.ps1 won't re-emit the same pattern hash.
#
# Implementation stays MANUAL: this tool records decisions; it does not patch
# kit files. That intentional gap is the safety boundary.
#
# Usage:
#   pwsh harness-review.ps1                           # list pending
#   pwsh harness-review.ps1 -All                      # list all (incl decided)
#   pwsh harness-review.ps1 -Show <proposal-id>       # print full body
#   pwsh harness-review.ps1 -ProposalId <id> -Action accept -Note "..."
#   pwsh harness-review.ps1 -ProposalId <id> -Action reject -Note "..."
#   pwsh harness-review.ps1 -ProposalId <id> -Action defer  -Note "next month"

param(
    [string]$ProposalId = "",
    [ValidateSet("", "accept", "reject", "defer")][string]$Action = "",
    [string]$Note = "",
    [string]$Show = "",
    [switch]$All,
    [switch]$Json
)

. (Join-Path $PSScriptRoot "_paths.ps1")

$proposalsDir = Join-Path $script:AgentsRoot "proposals"
$decisionsLog = Join-Path $proposalsDir "decisions.jsonl"
New-Item -ItemType Directory -Path $proposalsDir -Force | Out-Null

function Get-DecisionsMap {
    $map = @{}
    if (Test-Path $decisionsLog) {
        foreach ($line in Get-Content $decisionsLog -Encoding UTF8) {
            try {
                $d = $line | ConvertFrom-Json
                if ($d.proposal_id) { $map[$d.proposal_id] = $d }
            } catch {}
        }
    }
    return $map
}

function Get-ProposalMeta([string]$path) {
    $head = Get-Content $path -Encoding UTF8 -TotalCount 12 -ErrorAction SilentlyContinue
    $meta = @{}
    foreach ($l in $head) {
        if ($l -match "^(\w+):\s*(.+)$") { $meta[$Matches[1]] = $Matches[2].Trim() }
    }
    return $meta
}

# --- Show full proposal body ---
if ($Show) {
    $candidates = @(Get-ChildItem $proposalsDir -Filter "*.md" -ErrorAction SilentlyContinue |
        Where-Object { $_.Name -like "*$Show*" })
    if ($candidates.Count -eq 0) {
        Write-Error "No proposal found matching '$Show'"
        exit 1
    }
    foreach ($c in $candidates) {
        Write-Host "=== $($c.Name) ==="
        Get-Content $c.FullName -Encoding UTF8 | Out-Host
        Write-Host ""
    }
    exit 0
}

# --- Record a decision ---
if ($ProposalId -and $Action) {
    $files = @(Get-ChildItem $proposalsDir -Filter "*.md" -ErrorAction SilentlyContinue |
        Where-Object { $_.BaseName -eq $ProposalId -or $_.BaseName -like "*$ProposalId*" })
    if ($files.Count -eq 0) {
        Write-Error "Proposal '$ProposalId' not found in $proposalsDir"
        exit 1
    }
    if ($files.Count -gt 1) {
        Write-Error "Ambiguous proposal id '$ProposalId' -- matches: $(@($files | ForEach-Object { $_.BaseName }) -join ', ')"
        exit 1
    }
    $proposalFile = $files[0]
    $meta = Get-ProposalMeta $proposalFile.FullName

    $record = [ordered]@{
        proposal_id  = $proposalFile.BaseName
        pattern_hash = $meta.pattern_hash
        class        = $meta.class
        action       = $Action
        note         = $Note
        decided_at   = (Get-Date -Format "o")
        proposal_path = $proposalFile.FullName
    }
    Add-Content -Path $decisionsLog -Value (($record | ConvertTo-Json -Compress)) -Encoding UTF8

    # Update the proposal file's status header (best-effort)
    $body = Get-Content $proposalFile.FullName -Encoding UTF8 -Raw
    $body = $body -replace '(?m)^status:\s*\w+', "status: $Action"
    Set-Content -Path $proposalFile.FullName -Value $body -Encoding UTF8

    if ($Json) {
        Write-Output ($record | ConvertTo-Json -Compress)
    } else {
        Write-Host "Recorded: $($proposalFile.BaseName) -> $Action$(if ($Note) { " ($Note)" })"
        if ($Action -eq "accept") {
            Write-Host ""
            Write-Host "ACCEPTED. Implementation is manual -- review the proposal and apply the change yourself."
            Write-Host "  cat `"$($proposalFile.FullName)`""
        }
    }
    exit 0
}

# --- List proposals (default action) ---
$decisions = Get-DecisionsMap
$proposals = New-Object System.Collections.ArrayList

Get-ChildItem $proposalsDir -Filter "*.md" -ErrorAction SilentlyContinue | ForEach-Object {
    $meta = Get-ProposalMeta $_.FullName
    $decided = $decisions[$_.BaseName]
    $status = if ($decided) { $decided.action } elseif ($meta.status) { $meta.status } else { "pending" }
    [void]$proposals.Add([pscustomobject]@{
        id           = $_.BaseName
        class        = $meta.class
        seen_count   = $meta.seen_count
        generated_at = $meta.generated_at
        status       = $status
        note         = if ($decided) { $decided.note } else { "" }
        path         = $_.FullName
    })
}

if (-not $All) {
    $proposals = @($proposals | Where-Object { $_.status -eq "pending" })
}

if ($Json) {
    Write-Output (@{ proposals = @($proposals); count = $proposals.Count } | ConvertTo-Json -Compress -Depth 5)
} else {
    $scopeLabel = if ($All) { "All" } else { "Pending" }
    if ($proposals.Count -eq 0) {
        Write-Host "No $($scopeLabel.ToLower()) proposals."
    } else {
        Write-Host "$scopeLabel proposals: $($proposals.Count)"
        Write-Host ""
        foreach ($p in $proposals | Sort-Object generated_at -Descending) {
            $statusTag = switch ($p.status) {
                "pending"  { "[ ]" }
                "accept"   { "[A]" }
                "reject"   { "[R]" }
                "defer"    { "[D]" }
                default    { "[?]" }
            }
            Write-Host "$statusTag $($p.id)  class=$($p.class)  seen=$($p.seen_count)"
            if ($p.note) { Write-Host "    note: $($p.note)" }
        }
        Write-Host ""
        Write-Host "Show full text: pwsh harness-review.ps1 -Show <id>"
        Write-Host "Decide:         pwsh harness-review.ps1 -ProposalId <id> -Action accept|reject|defer -Note '...'"
    }
}
exit 0
