import { lstat, readFile, readdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";
import { parseFrontmatter, serializeFrontmatter, serializeToml } from "./parsers.js";
import { allAgents } from "./manifest.js";
import { atomicWriteContained, resolveContainedPath, resolveExistingContainedPath, unlinkContained } from "./paths.js";
import type { AgentDefinition, GeneratedFile, Host, Manifest, RenderOptions } from "./types.js";

export const GENERATED_MARKER = "@generated by Agentic Coding Kit v6";
const INVENTORY_PATH = "adapters/.agentic-kit-generated.json";
const MAX_SKILL_FILES = 100;
const MAX_SKILL_FILE_BYTES = 512 * 1024;
const MAX_SKILL_TOTAL_BYTES = 2 * 1024 * 1024;
const FORBIDDEN_RESOURCE_SEGMENTS = new Set([".git", ".kit", ".agentic-kit-backup", ".env", "node_modules", "vendor", "dist", "build", "coverage"]);

interface InventoryEntry { path: string; sourceId: string; sha256: string }
interface GeneratedInventory { schemaVersion: 1; marker: string; files: InventoryEntry[] }

export async function renderArtifacts(repoRoot: string, manifest: Manifest, options: RenderOptions): Promise<GeneratedFile[]> {
  const agents = options.installProfile === "full" ? allAgents(manifest) : manifest.agents;
  const files: GeneratedFile[] = [];
  const skillResources = new Map<string, Array<{ relativePath: string; sourcePath: string; content: string }>>();
  for (const skill of manifest.skills) skillResources.set(skill.id, await loadSkillResources(repoRoot, skill.id, skill.source));
  for (const host of ["codex", "claude", "opencode", "copilot"] as const) {
    for (const agent of agents.filter((candidate) => candidate.hosts.includes(host))) {
      const prompt = await readCanonical(repoRoot, agent.source);
      files.push(renderAgent(host, agent, prompt));
    }
    for (const skill of manifest.skills) {
      for (const resource of skillResources.get(skill.id)!) {
        files.push(renderSkillFile(host, skill.id, resource.relativePath, resource.sourcePath, resource.content));
      }
    }
    const orchestrator = await readCanonical(repoRoot, manifest.instruction_fragments.orchestrator);
    files.push(renderInstruction(host, manifest.instruction_fragments.orchestrator, orchestrator));
  }
  if (options.commands) {
    for (const skill of manifest.skills) files.push(renderOpenCodeCommand(skill.id));
  }
  files.sort((a, b) => a.path.localeCompare(b.path));
  files.push(renderInventory(files));
  return files.sort((a, b) => a.path.localeCompare(b.path));
}

export async function writeGenerated(repoRoot: string, files: GeneratedFile[]): Promise<void> {
  assertGeneratedDestinations(repoRoot, files);
  const previous = await loadGeneratedInventory(repoRoot);
  const expectedConflicts = await findExpectedConflicts(repoRoot, files, previous);
  if (expectedConflicts.length) throw new Error(`Modified or unowned expected-file conflict; refusing render:\n${expectedConflicts.join("\n")}`);
  const extras = await findGeneratedExtras(repoRoot, files, previous);
  if (extras.conflicts.length) throw new Error(`Modified generated-file conflict; refusing stale cleanup:\n${extras.conflicts.join("\n")}`);
  for (const extra of extras.removable) await unlinkContained(repoRoot, extra, "render root");
  for (const file of files) await atomicWriteContained(repoRoot, file.path, withoutBom(file.content), "render root");
}

export async function checkGeneratedDrift(repoRoot: string, files: GeneratedFile[]): Promise<string[]> {
  assertGeneratedDestinations(repoRoot, files);
  const previous = await loadGeneratedInventory(repoRoot);
  const expectedConflicts = await findExpectedConflicts(repoRoot, files, previous);
  const expectedConflictSet = new Set(expectedConflicts);
  const drift: string[] = [];
  for (const file of files) {
    try {
      const target = await resolveExistingContainedPath(repoRoot, file.path, "render root");
      const existing = await readFile(target, "utf8");
      if (withoutBom(existing) !== withoutBom(file.content) && !expectedConflictSet.has(normalizePath(file.path))) drift.push(file.path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") drift.push(file.path);
      else throw error;
    }
  }
  const extras = await findGeneratedExtras(repoRoot, files, previous);
  drift.push(...extras.removable, ...expectedConflicts.map((item) => `conflict:${item}`), ...extras.conflicts.map((item) => `conflict:${item}`));
  return drift;
}

function renderAgent(host: Host, agent: AgentDefinition, prompt: string): GeneratedFile {
  const sourceId = `agent:${agent.id}`;
  if (host === "codex") {
    const config: Record<string, unknown> = {
      name: agent.id,
      description: agent.description,
      developer_instructions: `${marker(agent.source, sourceId, "#")}\n${prompt.trim()}\n`,
      sandbox_mode: agent.permission_class === "read-only" ? "read-only" : "workspace-write",
    };
    return generated(`adapters/codex/agents/${agent.id}.toml`, `${marker(agent.source, sourceId, "#")}\n${serializeToml(config as never)}`, sourceId);
  }

  if (host === "claude") {
    const readOnly = agent.permission_class === "read-only";
    const data: Record<string, unknown> = {
      name: agent.id,
      description: agent.description,
      tools: readOnly ? ["Read", "Grep", "Glob", "Bash"] : ["Read", "Grep", "Glob", "Bash", "Edit", "Write"],
      model: "inherit",
      permissionMode: readOnly ? "plan" : "default",
      maxTurns: agent.model_tier === "premium" ? 16 : 12,
      effort: agent.model_tier === "premium" ? "high" : "medium",
    };
    return generated(`adapters/claude/agents/${agent.id}.md`, serializeFrontmatter(data, `${marker(agent.source, sourceId)}\n${prompt}`), sourceId);
  }

  if (host === "opencode") {
    const readOnly = agent.permission_class === "read-only";
    const data: Record<string, unknown> = {
      description: agent.description,
      mode: "subagent",
      permission: {
        edit: readOnly ? "deny" : "allow",
        bash: readOnly
          ? { "*": "ask", "git status*": "allow", "git diff*": "allow", "git show*": "allow", "git grep*": "allow" }
          : { "*": "ask" },
      },
    };
    return generated(`adapters/opencode/agents/${agent.id}.md`, serializeFrontmatter(data, `${marker(agent.source, sourceId)}\n${prompt}`), sourceId);
  }

  const data = { name: agent.id, description: agent.description, tools: copilotTools(agent.permission_class) };
  return generated(`adapters/copilot/agents/${agent.id}.agent.md`, serializeFrontmatter(data, `${marker(agent.source, sourceId)}\n${prompt}`), sourceId);
}

function renderSkillFile(host: Host, id: string, relativePath: string, sourcePath: string, source: string): GeneratedFile {
  const normalizedRelativePath = relativePath.split(path.sep).join("/");
  const sourceId = `skill:${id}:${normalizedRelativePath}`;
  const content = normalizedRelativePath === "SKILL.md"
    ? (() => {
        const parsed = parseFrontmatter(source);
        return serializeFrontmatter(parsed.data, `${marker(sourcePath, sourceId)}\n${parsed.content}`);
      })()
    : `${marker(sourcePath, sourceId)}\n${source.replace(/^\uFEFF/, "")}`;
  return generated(`adapters/${host}/skills/${id}/${normalizedRelativePath}`, content, sourceId);
}

function renderInstruction(host: Host, sourcePath: string, orchestrator: string): GeneratedFile {
  const hostNote = host === "copilot"
    ? "For Copilot, request the skill in natural language, inspect skills with `/skills`, and select custom agents with `/agent`."
    : host === "codex"
      ? "Use native skill selection or `$build`, `$design`, `$analyze`, `$review`, `$pr-ready`, `$threat-model`, and `$wiki`."
      : host === "claude"
        ? "Use the native `/build`, `/design`, `/analyze`, `/review`, `/pr-ready`, `/threat-model`, and `/wiki` skills."
        : "Use native skills or the optional thin slash-command forwarders.";
  const content = [
    marker(sourcePath, "instruction:orchestrator"),
    "<!-- agentic-coding-kit:start -->",
    orchestrator.trim(),
    "",
    `Host invocation: ${hostNote}`,
    "<!-- agentic-coding-kit:end -->",
    "",
  ].join("\n");
  return generated(`adapters/${host}/instructions.md`, content, "instruction:orchestrator");
}

function renderOpenCodeCommand(id: string): GeneratedFile {
  const source = `core/skills/${id}/SKILL.md`;
  const sourceId = `command:${id}`;
  const data = { description: `Run the Agentic Coding Kit ${id} skill` };
  const body = `${marker(source, sourceId)}\nLoad and follow the \`${id}\` skill for this request:\n\n$ARGUMENTS`;
  return generated(`adapters/opencode/commands/${id}.md`, serializeFrontmatter(data, body), sourceId);
}

function generated(filePath: string, content: string, sourceId: string): GeneratedFile {
  return { path: filePath, content: withoutBom(content), sourceId };
}

function marker(sourcePath: string, sourceId: string, prefix = "<!--"): string {
  return prefix === "#"
    ? `# ${GENERATED_MARKER}; source=${sourcePath}; sourceId=${sourceId}`
    : `<!-- ${GENERATED_MARKER}; source=${sourcePath}; sourceId=${sourceId} -->`;
}

function withoutBom(source: string): string {
  return source.replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
}

function copilotTools(permissionClass: AgentDefinition["permission_class"]): string[] {
  if (permissionClass === "read-only") return ["read", "search"];
  if (permissionClass === "test-write") return ["read", "search", "edit", "execute"];
  if (permissionClass === "workspace-write") return ["read", "search", "edit", "execute"];
  return ["read", "search", "edit", "execute"];
}

async function listFiles(root: string, prefix = ""): Promise<string[]> {
  const directory = path.join(root, prefix);
  const entries = await readdir(directory, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const relative = path.join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...await listFiles(root, relative));
    else if (entry.isFile()) files.push(relative);
  }
  return files;
}

async function findGeneratedExtras(repoRoot: string, expectedFiles: GeneratedFile[], previous: GeneratedInventory): Promise<{ removable: string[]; conflicts: string[] }> {
  const expected = new Set(expectedFiles.map((file) => normalizePath(file.path)));
  const removable: string[] = [];
  const conflicts: string[] = [];
  for (const entry of previous.files) {
    const filePath = normalizePath(entry.path);
    if (expected.has(filePath) || filePath === INVENTORY_PATH) continue;
    let content: string;
    try {
      const safeExisting = await resolveExistingContainedPath(repoRoot, filePath, "render root");
      content = await readFile(safeExisting, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
    if (!hasExactGeneratedHeader(content, entry.sourceId) || sha256(withoutBom(content)) !== entry.sha256) conflicts.push(filePath);
    else removable.push(filePath);
  }
  return { removable: removable.sort(), conflicts: conflicts.sort() };
}

async function findExpectedConflicts(repoRoot: string, expectedFiles: GeneratedFile[], previous: GeneratedInventory): Promise<string[]> {
  const priorByPath = new Map(previous.files.map((entry) => [normalizePath(entry.path), entry]));
  const conflicts: string[] = [];
  for (const file of expectedFiles) {
    if (file.path === INVENTORY_PATH) continue;
    const normalizedPath = normalizePath(file.path);
    const prior = priorByPath.get(normalizedPath);
    let content: string;
    try {
      const existing = await resolveExistingContainedPath(repoRoot, normalizedPath, "render root");
      content = await readFile(existing, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") continue;
      throw error;
    }
    if (!prior) {
      conflicts.push(normalizedPath);
      continue;
    }
    if (prior.sourceId !== file.sourceId || !hasExactGeneratedHeader(content, prior.sourceId) || sha256(withoutBom(content)) !== prior.sha256) conflicts.push(normalizedPath);
  }
  return conflicts.sort();
}

function normalizePath(filePath: string): string {
  return filePath.split(path.sep).join("/");
}

function assertGeneratedDestinations(repoRoot: string, files: GeneratedFile[]): void {
  for (const file of files) resolveContainedPath(repoRoot, file.path, "render root");
}

async function readCanonical(repoRoot: string, sourcePath: string): Promise<string> {
  const safeSource = await resolveExistingContainedPath(repoRoot, sourcePath, "repository root");
  return readFile(safeSource, "utf8");
}

export async function loadSkillResources(repoRoot: string, id: string, entrySource: string): Promise<Array<{ relativePath: string; sourcePath: string; content: string }>> {
  const entry = await resolveExistingContainedPath(repoRoot, entrySource, "repository root");
  const skillRoot = path.dirname(entry);
  const relativePaths = await listSkillFiles(skillRoot);
  if (relativePaths.length > MAX_SKILL_FILES) throw new Error(`Skill ${id} exceeds ${MAX_SKILL_FILES} resource files`);
  let totalBytes = 0;
  const resources = [];
  for (const relativePath of relativePaths) {
    const sourcePath = path.posix.join(path.posix.dirname(entrySource), relativePath.split(path.sep).join("/"));
    const safeSource = await resolveExistingContainedPath(repoRoot, sourcePath, "repository root");
    const stat = await lstat(safeSource);
    if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Unsafe skill resource: ${sourcePath}`);
    if (stat.size > MAX_SKILL_FILE_BYTES) throw new Error(`Skill resource exceeds ${MAX_SKILL_FILE_BYTES} bytes: ${sourcePath}`);
    totalBytes += stat.size;
    if (totalBytes > MAX_SKILL_TOTAL_BYTES) throw new Error(`Skill ${id} exceeds ${MAX_SKILL_TOTAL_BYTES} total bytes`);
    resources.push({ relativePath, sourcePath, content: await readFile(safeSource, "utf8") });
  }
  return resources;
}

async function listSkillFiles(root: string, prefix = ""): Promise<string[]> {
  const entries = await readdir(path.join(root, prefix), { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (FORBIDDEN_RESOURCE_SEGMENTS.has(entry.name)) continue;
    if (entry.isSymbolicLink()) throw new Error(`Symlink or junction is forbidden in canonical skill resources: ${path.join(prefix, entry.name)}`);
    const relative = path.join(prefix, entry.name);
    if (entry.isDirectory()) files.push(...await listSkillFiles(root, relative));
    else if (entry.isFile()) files.push(relative);
    if (files.length > MAX_SKILL_FILES) throw new Error(`Canonical skill exceeds ${MAX_SKILL_FILES} resource files`);
  }
  return files;
}

function renderInventory(files: GeneratedFile[]): GeneratedFile {
  const inventory: GeneratedInventory = {
    schemaVersion: 1,
    marker: GENERATED_MARKER,
    files: files.map((file) => ({ path: normalizePath(file.path), sourceId: file.sourceId, sha256: sha256(withoutBom(file.content)) })),
  };
  return generated(INVENTORY_PATH, `${JSON.stringify(inventory, null, 2)}\n`, "inventory");
}

async function loadGeneratedInventory(repoRoot: string): Promise<GeneratedInventory> {
  try {
    const inventoryPath = await resolveExistingContainedPath(repoRoot, INVENTORY_PATH, "render root");
    const parsed = JSON.parse(await readFile(inventoryPath, "utf8")) as Partial<GeneratedInventory>;
    if (parsed.schemaVersion !== 1 || parsed.marker !== GENERATED_MARKER || !Array.isArray(parsed.files)) throw new Error("invalid fields");
    for (const entry of parsed.files) {
      if (!entry || typeof entry.path !== "string" || typeof entry.sourceId !== "string" || !/^[a-f0-9]{64}$/.test(entry.sha256)) throw new Error("invalid entry");
      resolveContainedPath(repoRoot, entry.path, "render root");
    }
    return parsed as GeneratedInventory;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return { schemaVersion: 1, marker: GENERATED_MARKER, files: [] };
    throw new Error(`Generated inventory conflict; refusing cleanup: ${(error as Error).message}`);
  }
}

function hasExactGeneratedHeader(content: string, sourceId: string): boolean {
  const escaped = sourceId.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const header = new RegExp(`^(?:# ${GENERATED_MARKER}; source=[^;\\r\\n]+; sourceId=${escaped}|<!-- ${GENERATED_MARKER}; source=[^;\\r\\n]+; sourceId=${escaped} -->)$`);
  return content.replace(/\r\n/g, "\n").split("\n").some((line) => header.test(line));
}

function sha256(content: string): string {
  return createHash("sha256").update(content, "utf8").digest("hex");
}
