import { readFile } from "node:fs/promises";
import path from "node:path";
import { parseFrontmatter, parseToml } from "./parsers.js";
import type { GeneratedFile, Manifest } from "./types.js";

const PROMPT_BUDGETS = {
  orchestrator: { words: 850, bytes: 6 * 1024 },
  opencodePrimary: { words: 120, bytes: 2 * 1024 },
  skill: { words: 650 },
  agent: { words: 300 },
} as const;

export async function validateCanonicalPrompts(repoRoot: string, manifest: Manifest): Promise<void> {
  const promptPaths = [
    manifest.instruction_fragments.orchestrator,
    manifest.instruction_fragments.opencode_primary,
    ...manifest.agents.map((agent) => agent.source),
    ...Object.values(manifest.packs).flatMap((pack) => pack.agents.map((agent) => agent.source)),
    ...manifest.skills.map((skill) => skill.source),
  ];
  const forbidden: Array<[RegExp, string]> = [
    [/\.kit[\\/]/i, "legacy .kit runtime path"],
    [/\/goal\b/i, "portable goal workflow"],
    [/gpt-\d/i, "provider model ID"],
    [/--mode\s+(feature|fix|refactor|migration|ui|config)/i, "public build mode"],
    [/--diagnose-only/i, "diagnosis-only build flag"],
  ];
  for (const sourcePath of promptPaths) {
    const content = await readFile(path.join(repoRoot, sourcePath), "utf8");
    if (content.charCodeAt(0) === 0xfeff) throw new Error(`UTF-8 BOM in ${sourcePath}`);
    assertPromptBudget(sourcePath, content, manifest);
    for (const [pattern, label] of forbidden) {
      if (pattern.test(content)) throw new Error(`${sourcePath} contains forbidden ${label}`);
    }
  }
}

function assertPromptBudget(sourcePath: string, content: string, manifest: Manifest): void {
  const budget = sourcePath === manifest.instruction_fragments.orchestrator
    ? PROMPT_BUDGETS.orchestrator
    : sourcePath === manifest.instruction_fragments.opencode_primary
      ? PROMPT_BUDGETS.opencodePrimary
      : /(?:^|\/)SKILL\.md$/.test(sourcePath.replaceAll("\\", "/"))
        ? PROMPT_BUDGETS.skill
        : PROMPT_BUDGETS.agent;
  const words = content.match(/\S+/g)?.length ?? 0;
  if (words > budget.words) {
    throw new Error(`${sourcePath} exceeds prompt budget: ${words} words > ${budget.words}`);
  }
  if ("bytes" in budget) {
    const bytes = Buffer.byteLength(content, "utf8");
    if (bytes > budget.bytes) {
      throw new Error(`${sourcePath} exceeds prompt budget: ${bytes} bytes > ${budget.bytes}`);
    }
  }
}

export function validateGeneratedArtifacts(files: GeneratedFile[]): void {
  const paths = new Set<string>();
  for (const file of files) {
    if (paths.has(file.path)) throw new Error(`Duplicate generated path: ${file.path}`);
    paths.add(file.path);
    if (file.content.charCodeAt(0) === 0xfeff) throw new Error(`UTF-8 BOM in ${file.path}`);
    if (!file.content.includes("@generated by Agentic Coding Kit v6")) throw new Error(`Missing generated marker: ${file.path}`);
    if (file.path.endsWith(".toml")) parseToml(file.content);
    if (file.path.endsWith(".json")) {
      const parsed = JSON.parse(file.content) as Record<string, unknown>;
      if (parsed.marker !== "@generated by Agentic Coding Kit v6") throw new Error(`Invalid generated inventory: ${file.path}`);
    }
    const hasFrontmatter = file.path.endsWith(".md") && (file.path.includes("/agents/") || file.path.includes("/commands/") || file.path.endsWith("/SKILL.md"));
    if (hasFrontmatter) {
      const parsed = parseFrontmatter(file.content);
      if (!parsed.data.description && !file.path.endsWith("SKILL.md")) throw new Error(`Missing description: ${file.path}`);
      if (file.path.endsWith("SKILL.md") && (!parsed.data.name || !parsed.data.description)) throw new Error(`Invalid skill frontmatter: ${file.path}`);
    }
  }
}
